### PR TITLE
add new bpatchers, new ll.r~ updates (one stereo receive per "row")

### PR DESCRIPTION
**Pull request by the-steech**
created some new bpatchers specifically for sending vol & pan values as list params (list number == channel)
use an ll.r~ for each input row

edit: this also removed the unnecessary "createGains.js" file

### CODE REVIEW

**Comment by klausfilip** [comment]
hmm, yes, well should work ;)
but its a bit of a nightmare;)
have a look into matrix@, it uses a single ll.r~, that gets a channel-count depending on the amount of input channels (and mono/stereo).

**Comment by klausfilip** [comment]
i am not sure, what i should do here. how can i give my OK for the merge? and how can i suggest an update for example getting rid of the old inputs~

**Comment by the-steech** [comment]
i have this for readability!  i want to select the in_# that matches the red number on the left :).  

it's a little easier to select a stereo pair for row "5" using in_5.1, in_5.2-- rather than in.9, in.10 ( in my opinion ;)... )

**Comment by klausfilip** [comment]
ok!! there is a sticky old entry in inputs~. go into the clientwindow and delete the in(32) at the end of the inputs~list.

**Comment by the-steech** [comment]
thanks klaus :)  just removed that sticky in(32) to this branch

**Pull request merged**
